hybris/egl/egl.c

eglGetprocAddress currently just returns the value it gets from the
android EGL if the procname isn't one of few special functions.
This has two issues:
1) Android's eglGetProcAddress returns garbage for core gl functions.
2) The calling convenction is different, which means float arguments
to the returned functions will not work correctly.
To fix this get the symbols with the glibc's dlsym, using RTLD_DEFAULT
as library handle. If that fails we fall back to returning the value
of eglGetProcAddress, which may be sane.

dlsym the symbols in eglGetProcAddress from the glibc libraries

---

hybris/common/hooks.c

Fix typo in hooks

---

.gitignore

Signed-off-by: Marko Saukko <marko.saukko@jolla.com>

Ignore some more generated files.

---

hybris/egl/platforms/common/eglplatformcommon.cpp
hybris/glesv2/glesv2.c

These two patches fix two different problems i encountered when playing with a gl app. Explanations in the commit messages.

Two (E)GL fixes

---

hybris/Makefile.am
hybris/common/Makefile.am
hybris/common/hooks.c
hybris/common/jb/dlfcn.c
hybris/common/jb/linker.c
hybris/configure.ac
hybris/egl/platforms/Makefile.am
hybris/egl/platforms/common/Makefile.am
hybris/egl/platforms/hwcomposer/Makefile.am
hybris/egl/platforms/wayland/Makefile.am
hybris/libnfc_nxp/libnfc_nxp.c
hybris/tests/Makefile.am
hybris/tests/test_gps.c

Signed-off-by: Carsten Munk <carsten.munk@jollamobile.com>

Add Android 5.0 support - tested on 5.1

---

hybris/egl/platforms/hwcomposer/Makefile.am
hybris/egl/platforms/hwcomposer/hwcomposer.h
hybris/egl/platforms/hwcomposer/hwcomposer_window.cpp

The existing API was only usable in C++ projects.

Add API for using hwcomposer windows in C code

---

utils/extract-headers.sh

Signed-off-by: You-Sheng Yang <vicamo@gmail.com>

utils: fix dash "need redirection"

---

hybris/common/hooks.c

Signed-off-by: Lorn Potter <lorn.potter@jollamobile.com>

add scandir, scandirat, alphasort, versionsort hooks

---

hybris/egl/egl.c
hybris/egl/platforms/null/eglplatform_null.c
hybris/hardware/hardware.c
hybris/vibrator/vibrator.c

This is a re-try after backed out in #307.

use global hybris macros whenever available

---

hybris/common/dlfcn.c
hybris/common/gingerbread/debugger.c
hybris/common/hooks.c
hybris/common/hooks_shm.c
hybris/common/jb/debugger.c
hybris/common/jb/dlfcn.c
hybris/egl/egl.c
hybris/egl/platforms/fbdev/eglplatform_fbdev.cpp
hybris/egl/platforms/fbdev/fbdev_window.cpp
hybris/egl/platforms/hwcomposer/eglplatform_hwcomposer.cpp
hybris/egl/platforms/hwcomposer/hwcomposer_window.cpp
hybris/egl/platforms/null/eglplatform_null.c
hybris/egl/platforms/wayland/eglplatform_wayland.cpp
hybris/egl/platforms/wayland/wayland_window.cpp
hybris/include/hybris/common/dlfcn.h
hybris/properties/cache.c
hybris/tests/test_sensors.c

Closes: #304
Signed-off-by: You-Sheng Yang <vicamo@gmail.com>

libhybris: fix various compile time warnings

---

compat/input/direct_input_test.cpp
compat/surface_flinger/direct_sf_test.cpp

direct_input_test is defined in https://github.com/libhybris/libhybris/blob/master/compat/input/Android.mk#L52 but the file does not exist. This adds that file.
direct_sf_test.cpp  is defined in https://github.com/libhybris/libhybris/blob/master/compat/surface_flinger/Android.mk#L30

Add missing file from compat: direct_input_test.cpp

---

hybris/tests/test_hwcomposer.cpp

This patch has been used in many Sailfish OS devices for a while now and found to be working well.

[test_hwcomposer] Add support for hwcomposer 1.3, 1.4 and 1.5.

---

hybris/egl/platforms/fbdev/fbdev_window.cpp

If a sync fence is provided in queueBuffer, we have to wait for it to signal (for vsync) and close it (so that fd's are not leaking).

fbdev_window: wait for fence to be signalled and close it

---

hybris/common/hooks.c

Check FILE stream for validity before call fflush. fix #372 issue

Fix fflush segfault

---

hybris/common/mm/linker.cpp
hybris/common/n/linker.cpp

Fixes this issue: https://github.com/libhybris/libhybris/issues/357
Credits go to @ruleh

Fix nullpointer crashes in strcmp

---

hybris/common/hooks.c
hybris/gralloc/GrallocUsageConversion.cpp
hybris/gralloc/gralloc.c

This only affects android 8 adaptations.

Fix release imply delete and sdkversion

---

hybris/common/jb/linker.c
hybris/common/mm/linker.cpp

Improve gdb support to Android jb/mm linker
With default bionic's implementation, the list of loaded libraries
for GDB is reset when the first Android lib is loaded.
With libhybris, we want to get both Android and Glibc loaded libraries.
However, we shouldn't simply link our "link_map" pointers in the
current list, because glibc's "link_map" object shouldn't point to
our incompatible "link_map" objects. To avoid that:
1. make a copy of the initial list, to avoid modifying glibc's objects
2. prepend our objects to the list, instead of appening it
That way glibc's objects are never modified, and glibc's linker won't
try to manipulate objects that haven't been initialized by him.

Apply gdb debugging support also to jb and mm linkers.

---

utils/extract-headers.sh

Mer's version from https://github.com/mer-hybris/droid-hal-device/blob/master/helpers/extract-headers.sh add support for Android 8 & 9 (Oreo & Pie) as well as some error handling. Since Halium and projects using Halium are looking into Android 8 & 9 based ports, it's good to update the script to cover these headers as well.
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

extract-headers.sh: Use version from Mer (Adds Android 8 & 9 support)

---

hybris/properties/hybris_properties.c

This adds fallback to own property implementation if libc is not present
instead of aborting. This is needed as libhybris may be linked on non
hybris devices where we use getprop to determine what device type we are
running on.

Fallback to own property implementation if libc is not present

---

compat/camera/direct_camera_test.cpp
compat/media/direct_media_test.cpp
compat/media/media_format_layer_priv.cpp
hybris/common/hooks.c
hybris/common/mm/linker.cpp
hybris/common/mm/linker_phdr.cpp
hybris/common/n/linker_phdr.cpp
hybris/common/o/linker.cpp
hybris/common/o/linker_cfi.cpp
hybris/common/o/linker_config.cpp
hybris/common/o/linker_phdr.cpp
hybris/common/o/linker_soinfo.cpp
hybris/egl/platforms/hwcomposer/hwcomposer_window.cpp
hybris/libsync/sync_test.c
hybris/tests/test_camera.cpp
hybris/tests/test_recorder.cpp

Addresses various warnings that were found by CppCheck/Codacy.
Signed-off-by: Herman van Hazendonk github.com@herrie.org

Cleanup warnings in found by CppCheck/Codacy

---

hybris/autogen.sh
utils/extract-headers.sh
utils/generate_glesv1/generate_wrappers.py
utils/travis-build.sh

Various fixes based on Codacy checking.
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

.sh and .py script fixes

---

hybris/common/hooks.c

waste a little bit less memory if adreno quirks is enabled

hooks: improve adreno quirks

---

hybris/tests/Makefile.am

egl: tests: Add libhardware to ld flags

---

hybris/common/Makefile.am
hybris/common/wrapper_code_generic_arm.c
hybris/common/wrappers.c
hybris/configure.ac

This ports ARM function calls tracing support for AArch64.

hybris: introduce ARM64 support for HYBRIS_TRACE_(DYNHOOKED/UNHOOKED/HOOKED)

---

utils/extract-headers.sh

Which adds Android 11 support and has some minor cleanups:
Original at: https://github.com/mer-hybris/droid-hal-device/blob/master/helpers/extract-headers.sh
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

extract-headers.sh: Update with version from Mer

---

hybris/egl/Makefile.am

Fixes https://github.com/libhybris/libhybris/issues/510

hybris: egl: Fix glvnd build

---

hybris/platforms/common/server_wlegl.cpp

server_wlegl: fix a crash when format = 0.

---

hybris/egl/platforms/fbdev/fbdev_window.cpp
hybris/egl/platforms/fbdev/fbdev_window.h
hybris/egl/platforms/hwcomposer/hwcomposer_window.cpp
hybris/egl/platforms/hwcomposer/hwcomposer_window.h
hybris/platforms/common/platformcommon.cpp
hybris/platforms/common/server_wlegl.cpp
hybris/platforms/common/server_wlegl_buffer.cpp
hybris/platforms/common/server_wlegl_buffer.h
hybris/platforms/common/windowbuffer.h
hybris/platforms/wayland/wayland_window_common.cpp
hybris/platforms/wayland/wayland_window_common.h

Also add some missing locks to wayland platform code.

Use 64-bit variables for usage where necessary
