- hybris/egl/egl.c
- hybris/egl/eglhybris.h
- hybris/egl/platforms/fbdev/eglplatform_fbdev.cpp
- hybris/egl/platforms/hwcomposer/eglplatform_hwcomposer.cpp
- hybris/egl/platforms/null/eglplatform_null.c
- hybris/egl/platforms/wayland/eglplatform_wayland.cpp
- hybris/egl/platforms/wayland/wayland_window.cpp
- hybris/egl/platforms/wayland/wayland_window.h
- hybris/egl/ws.c
- hybris/egl/ws.h
This extension allows a nested compositor to create a client side
buffer for a server side buffer resource, and to post it to the parent
compositor on a subsurface, outsourcing compositing of the client surface
to the parent.
We also wrap EGLImageKHR with an internal struct to store the buffer that
image was created from, which we use later to create the wl_buffer.
> Implement the EGL_WL_create_wayland_buffer_from_image extension

- hybris/egl/platforms/common/wayland-egl.c
If wl_egl_window_destroy is called before WaylandNativeWindow construction,
wl_egl_window_destroy will try to call free_callback through an uninitialized
pointer.
> [libhybris] Initialize egl_window->free_callback

- hybris/egl/platforms/wayland/eglplatform_wayland.cpp
The EGL spec defines the conditions in which the function can fail. Some
applications like chromium can actually cope with the fact that an early
eglQueryString function call failed and can retry it at a later time.
Unfortunately current implementation of EGL in libhybris simply aborts
exeution of the app in such case. This patch removes such bogus assert
propagating the NULL return value to the caller instead.
> Propagate eglQueryString error back to the caller instead of crashing.

- hybris/egl/egl.c
- hybris/egl/platforms/wayland/eglplatform_wayland.cpp
- hybris/egl/ws.c
- hybris/egl/ws.h
This basically reverts 4c6d9966187e561a2e6b821aee0e90c11f413e9a.
Acording to Gunnar Sletta the patch was a workaround for a bug in gecko.
Since the problem was fixed there is no point in keeping it around.
Passing invalid pointers to EGL functions should not be an acceptable
behaviour.
> Get rid of workaround allowing gecko to pass invalid pointers to EGL.

- hybris/glesv2/Makefile.am
- hybris/glesv2/glesv2.c
Current implementation of EGL in libhybris wrapps EGLImage objects
received from android layer into a custom data structure. This means
that the object needs to be unwrapped properly before being passed back
to android EGL funcrion calls. This was done in hybris implementation of
libEGL, but not in libGLESv2. As a result whenever application (gecko in
this case) tried to use libGLESv2 version of EGLImageTargetTexture2DOES
it would fail with GL_INVALID_OPERATION.
> Unwrap EGLImage before passing it to android layer. JB#29670

- hybris/egl/egl.c
Previously we just looked up the process-global namespace for the functions, so looking up symbols only worked if the process also had the right `libGLES*.so` loaded.
EGL on other platforms doesn't need this, so make sure that we load the right library dynamically and return symbols from it. The library loaded is still the libhybris (glibc-based) one due to the hardfp calling convention.
This also avoids issues where `eglGetProcAddress()` would return any symbols in the global symbol namespace of the dynamic linker.
> [egl] eglGetProcAddress should return symbols of chosen EGL config

- hybris/common/hooks.c
We are already hooking up bionic __cxa_atexit to the glibc one.
Not hooking __cxa_finalize is a bug because the bionic one will go
and try to finalize stuff it did not manipulate causing a crash
upon unloading some shared objects
> Hook __cxa_finalize as well.

- hybris/common/jb/dlfcn.c
We need that to prevent hybris from wrongly
unloading libdl.so when an application exits.
> set libdl soinfo refcnt to 1

- hybris/hardware/hardware.c
Look for libhardware.so from default search path instead of hardcoding the path so we can use a patched version of libhardware.so from /usr/libexec/droid-hybris/system/lib/.
> Look for libhardware.so from default search path.

- hybris/egl/platforms/common/server_wlegl.cpp
Fixes #286 about server-side wayland buffers not working on devices using QCOM_BSP.
> [egl] Add missing android-config.h include.

- hybris/glesv2/glesv2.c
This reverts commit 295d1598b500f9d7663a77d5ef458936b5bad24f.
In some cases this would crash during gnu_indirect_function relocation,
and always reproducable with LD_BIND_NOW=1.
==5550== Jump to the invalid address stated on the next line
==5550==    at 0x2C26: ???
==5550==    by 0xA1CB5C5: ??? (in /usr/libexec/droid-hybris/system/lib/libEGL.so)
==5550==    by 0x735A3BD: pthread_once (pthread_once.S:120)
==5550==    by 0xA1C8101: ??? (in /usr/libexec/droid-hybris/system/lib/libEGL.so)
==5550==    by 0x7FCD240: call_array (linker.c:1553)
==5550==    by 0x7FD446C: call_constructors_recursive (linker.c:1618)
==5550==    by 0x7FD4347: call_constructors_recursive (linker.c:1602)
==5550==    by 0x7FCCF3A: android_dlopen (dlfcn.c:64)
==5550==    by 0x73487E9: glIsFramebuffer (glesv2.c:246) …
> Revert "Fix calling gl* functions without loading them with eglGetProcAddress". Fixes NEMO#844

- hybris/glesv2/glesv2.c
The issue was addressed in 295d159 but that commit had to be reverted by
c1099bd because of a crash when trying to dlopen the wrapped libGLESv2.so.
Instead, if a gl* function is resolved when we don't have yet a handle for
the library, use a wrapper calling the internal function.
> Fix resolving the GLEsv2 functions at link time

- utils/extract-headers.sh
Header extraction passed on following tags:
* android-2.3.7_r1
* android-4.0.4_r2.1
* android-4.1.2_r2.1
* android-4.2.2_r1.2
* android-4.3_r3.1 [1]
* android-4.4.4_r2.0.1
* android-5.0.2_r3
* android-5.1.1_r13
Build [2] passed on:
* android-4.2.2_r1.2
* android-4.3_r3.1
* android-4.4.4_r2.0.1
* android-5.0.2_r3
* android-5.1.1_r13
Note 1: specify __MAJOR__, __MINOR__, and __PATCH__ as `./utils/extract-headers.sh aosp/android-4.3_r3.1 android-headers 4 3 0` because AOSP 4.3 has a 2-digit PLATFORM_VERSION "4.3" rather than "4.3.0".
Note 2: configured by `hybris/autogen.sh --with-android-headers=`pwd`/android-headers --prefix=/usr --with-default-egl-platform=hwcomposer --enable-debug --enable-trace --with-default-hybris-ld-library-path=/system/lib:/vendor/lib`
> utils: fix android headers extraction

- hybris/configure.ac
- hybris/properties/Makefile.am
- hybris/properties/properties.c
- hybris/properties/properties_p.h
- hybris/properties/runtime_cache.c
Android properties are looked up over socket connection by default,
which incurs considerable overhead if property lookup is very frequent.
This commit adds similar property cache to socket based lookups as is
used for direct file lookups. The cache invalidates its contents with
a user definable timeout, making sure property changes are eventually
propagated to all processes.
By default the cache is not enabled, but can be enabled with
--enable-property-cache configure switch.
> [libhybris] Add cache for socket based property lookups.

- hybris/common/jb/dlfcn.c
- hybris/common/jb/linker.c
- hybris/common/jb/linker.h
Fails with
dlfcn.c:202:17: error: initializer element is not constant
dlfcn.c:202:17: note: (near initialization for 'libdl_symtab[1].st_value')
dlfcn.c:207:17: warning: cast from pointer to integer of different size
[-Wpointer-to-int-cast]
st_value: (Elf32_Addr) &android_dlclose,
> hybris/common/jb: Making libhybris buildable x86 64

- hybris/configure.ac
- hybris/libnfc_nxp/libnfc_nxp.c
- hybris/tests/Makefile.am
- hybris/tests/test_audio.c
- hybris/tests/test_gps.c
- hybris/tests/test_nfc.c
- hybris/tests/test_sensors.c
This fix build against [Android API level](http://developer.android.com/guide/topics/manifest/uses-sdk-element.html) 14-23 using headers extracted in https://git.launchpad.net/~vicamo/android-headers/+git/android-headers/log/?h=clean .
Closes #298, #185.
> Fix build against API level >= 14

- utils/extract-headers.sh
* NFC headers is only available since v2.3 (API level 9)
* kernel headers was in bionic/ before v2.3 (API level 9)
Android API level tested: 4-10, 14-23
Signed-off-by: You-Sheng Yang <vicamo@gmail.com>
> utils: fix header extraction for ancient versions

- hybris/egl/egl.c
- hybris/egl/platforms/null/eglplatform_null.c
- hybris/hardware/hardware.c
- hybris/vibrator/vibrator.c
This patch tries to reduce the amount of manual work and cut possible inconsistency.
> use global hybris macros whenever available

- hybris/egl/egl.c
- hybris/egl/platforms/null/eglplatform_null.c
- hybris/hardware/hardware.c
- hybris/vibrator/vibrator.c
With commit a6668d293c00b18b7cb755a0c7a600a56bc63339, on Sailfish OS lipstick (Wayland compositor) still works, but any clients (apps) crash upon start with ```Fatal: the server doesn't advertise the android_wlegl global!Aborted```
This PR reverts commit a6668d293c00b18b7cb755a0c7a600a56bc63339.
Thanks to @mlehtima for finding this
> Revert "use global hybris macros whenever available"

- hybris/tests/test_hwcomposer.cpp
open FB HAL before HWC, fixes HWC for some devices (e.g. rockchip tvboxes): based on comment in surfaceflinger sources: https://android.googlesource.com/platform/frameworks/native/+/master/services/surfaceflinger/DisplayHardware/HWComposer.cpp#108
> open FB HAL before HWC, fixes HWC for some devices

- hybris/glesv2/glesv2.c
The a38512b7 introduces logic, when GLES2_IDLOAD(func) could refer
to func_wrapper and invoke _func, which is set in constructor
via GLES2_LOAD. For some reason GLES2_LOAD is not invoked for
glReadPixels.
Signed-off-by: Alex Hoppus <alexhoppus111@gmail.com>
> Putting GLES2_LOAD(glReadPixels) to initialization sequence

- utils/extract-headers.sh
It seems Android v6 has dropped patch level from the version number.
Handle this by haveing extract-headers.sh default to patch level 0,
if missing.
> utils/extract-headers.sh: Don't fail on PLATFORM_VERSION := 6.0

- hybris/properties/properties.c
All the system properties of length 31 were not accepted and the Android layer had no knowledge of them. It was found by rinigus on Nexus4, where the microphone was selected improperly because the persist.audio.fluence.voicecall property (set to 'true') had exactly 31 characters.
> [properties] An off-by-one error in prop handling

- utils/extract-headers.sh
The use of `tee <<EOF` means that the shell ${} variables in the
heredoc are expanded causing compilers to look in the wrong directory,
e.g.:
```
Name: Android header files
Description: Header files needed to write applications for the Android platform
Version: 5.1.51
prefix=/usr
exec_prefix=
includedir=/include
Cflags: -I/android
```
These variables should not be interpreted when written to the
android-headers.pc file, so use the form `tee <<'EOF'`.
Tested when /bin/sh is a symlink to bash and dash.
This was broken in:
commit f597786ae48f6d7fa13bcd3ef8b6f8873d05439f
utils: fix dash "need redirection"
Signed-off-by: Daniel Cordero <libhybris@xxoo.ws>
> extract_headers.sh: Do not escape android-headers.pc

- hybris/glesv2/glesv2.c
libhybris doesn't expose any 3.0+ symbols so client code, like Qt,
becomes confused.
> [glesv2] Wrap glGetString() and return GL_VERSION == 2.0.

- hybris/egl/platforms/common/eglplatformcommon.cpp
- hybris/egl/platforms/wayland/eglplatform_wayland.cpp
Larger buffer is needed on some hybris-13.0 based devices. At least on Samsung Galaxy Tab 4 WiFi the buffer is too short and last entry in the list is cut in half causing apps using Wayland EGL to fail.
> [egl] Increase buffer size for EGL extensions.

- hybris/common/hooks.c
memcpy has to always return dst
see "man memcpy" and bionic/libc/arch-arm/generic/bionic/memcpy.S
with this and the ported mm linker test_hwcomposer, minimer and lipstick work on mako with cm13 based adaptation.
> fix for future cm13 based adaptations

- hybris/common/hooks.c
to avoid a crash on exit of most programs
> hybris: fix mismatch between bionic fpos_t size and glibc fpos_t in bionic_file struct

- hybris/common/jb/linker.c
If HYBRIS_LINKER_FORCE_BASENAME is set, then the linker will first
look for the .so based on the basename of the library, in case an
absolute path has been given.
This way it is possible to redirect .so loading even for absolute paths.
> linker: introduce HYBRIS_LINKER_FORCE_BASENAME for .so search

- utils/extract-headers.sh
For my Asus Zenwatch 3, I needed these additional headers to build AsteroidOS. As there is no matching branch for Wear 1.5, I used the marshmallow-dr1.5-release branch for building the Android parts. Hence, I don't know how relevant these headers are for "normal" marshmallow-based Androids.
> add additional headers in extract-headers.sh for wear 1.5

- hybris/common/hooks.c
The two "buf" variables don't need to be stored in TLS or to be global,
as they are only used as intermediate variables for the final glibc call.
Therefore remove the "static __thread" prefixes for these two.
Note: In my case having these two TLS variables did also lead to crashes when the
"tls_hooks" TLS variable is returned in the get_tls_hooks function. However
I couldn't determine conclusively why it crashed in that case.
> hooks: remove unneeded TLS variable

- hybris/common/hooks.c
> hooks: include mm hooks only when WANT_LINKER_MM is defined

- utils/extract-headers.sh
Earlier it didn't install the log directory, which resulted in failure
if headers are installed to system-wide location
> Fix the makefile generated by the extract-headers.sh script

- utils/extract-headers.sh
This header was previously extracted with Android 6 only but it is available since 4.1.
The wifi module compilation is not set to be compiled only for Android 6.
That permit to fix compilation issue with older version than 6 on wifi.c :
wifi.c:23:34: fatal error: hardware_legacy/wifi.h: No such file or directory
Tested with AOSP 5.1.1_r30 with success
> utils: hardware_legacy/wifi.h needs to be extracted for AOSP 4.1+

- hybris/tests/Makefile.am
- hybris/tests/test_vibrator.c
Needed on Android 7 based devices because legacy header was removed.
> [test_vibrator] Add support for new Android vibrator API.

- hybris/common/mm/linker.cpp
On some device, a binary blob call dlopen with "egl/blah.so". The
correct behavior (and current code's behavior) is to open the library
directly on that path (relative to working directory) and don't look in
library path.
But the sad truth of life is, some binary blob rely on old behavior
which will not open the library directly if the path doesn't start
with '/'. As the library is actually reside in /system/vendor/lib/egl/,
the code will work with old behavior and not new behavior.
This commit makes linker search for library in library path if it can't
open library directly, which is the behavior of Android 5.0's linker.
This will let those libraries work.
This is the reference of this behavior:
https://android.googlesource.com/platform/bionic/+/6971fe4ca52ebdaa85ba676a044412b01d2ef1bf
> hybris: common: mm: search lib in library path if opening directly fails.

- hybris/common/Makefile.am
- hybris/common/hooks.c
- hybris/common/jb/Makefile.am
- hybris/common/jb/linker.c
- hybris/common/mm/Makefile.am
- hybris/common/mm/dlfcn.cpp
- hybris/common/mm/linker.cpp
- hybris/common/wrapper_code.h
- hybris/common/wrapper_code_generic_arm.c
- hybris/common/wrappers.c
- hybris/common/wrappers.h
- hybris/configure.ac
useful to trace calls to and between android blobs.
shows you (somewhat) what the blobs are actually doing
works for functions which have no debug hook (HOOK_DIRECT_NO_DEBUG) but cannot print arguments, nevertheless i found it useful many times
implemented by injecting a wrapper function between a function that is called and it's actual implementation
it is entirely optional (--enable-mm-arm-tracing)
for example you could run
HYBRIS_TRACE_UNHOOKED=1 test_egl
and IF it would say: calling unhooked method malloc@ptr
you would know that malloc is unhooked (which it shouldn't be) and is called.
if for example test_egl crashes you could run
HYBRIS_TRACE_HOOKED=1 test_egl
and if you're lucky it would tell you maybe: calling hooked method foo@ptr with a crash immediately afterwards -> it's likely …
> hybris (arm): introduce HYBRIS_TRACE_(DYNHOOKED/UNHOOKED/HOOKED)

- compat/surface_flinger/surface_flinger_compatibility_layer.cpp
- hybris/include/hybris/surface_flinger/surface_flinger_compatibility_layer.h
- hybris/sf/sf.c
- hybris/tests/Makefile.am
Reintroduce test_sf (previously dropped and partially "reverted" later)
Add 2 new functions to sf that are independent and will not break existing code :
- sf_get_display_info
- sf_client_get_egl_context
sf_get_display_info :
permit to get more details that are not necessary available with current code that requesting the framebuffer. We directly do the request to SurfaceFlinger.
sf_client_get_egl_context : 
permit to get the EGL context of a SfClient. This is useful for QPA.
> sf: 2 new functions and test_sf

- hybris/common/mm/dlfcn.cpp
some code depends on dlerror() returning NULL when dlsym succeeds.
> dlerror() should return NULL on success

- hybris/common/Makefile.am
- hybris/common/hooks.c
- hybris/configure.ac
If this is enabled malloc(4) will be treated as if it was malloc(5).
This introduces overhead obviously but solves the following problem:
If sailfishos-browser crashes for no reason with shader compilation
errors this is required. It is most likely a bug in the blobs since
we only experience it on a subset of devices. Also using a jemalloc
implementation as LD_PRELOAD to libhybris works around this problem.
jemalloc is used in android which seems to indicate that it is more
lenient with these kinds of out-of-bounds accesses.
NOTE: sailfishos-browser is not the only affected app, it is just
an example. lipstick and others are also affected but it is not as
noticeable. Reboot/UI-restart is necessary after this change.
> hybris: introduce --enable-adreno-quirks

- hybris/egl/platforms/common/nativewindowbase.cpp
- hybris/egl/platforms/common/nativewindowbase.h
- hybris/egl/platforms/fbdev/fbdev_window.cpp
- hybris/egl/platforms/fbdev/fbdev_window.h
- hybris/egl/platforms/hwcomposer/hwcomposer_window.cpp
- hybris/egl/platforms/hwcomposer/hwcomposer_window.h
- hybris/egl/platforms/wayland/wayland_window.cpp
- hybris/egl/platforms/wayland/wayland_window.h
add querys NATIVE_WINDOW_DEFAULT_DATASPACE and NATIVE_WINDOW_CONSUMER_USAGE_BITS. Some devices fail to create a hwcomposer/fbdev window without this.
> nativewindowbase: fix hwcomposer/fbdev window creation on some devices

- hybris/common/n/linker.cpp
Addresses the following issues with newer glibc
linker.cpp: In member function 'bool soinfo::relocate(const
VersionTracker&, ElfRelIteratorT&&, const soinfo_list_t&, const
soinfo_list_t&)':
linker.cpp:3156:12: error: 'R_AARCH64_TLS_TPREL64' was not declared in
this scope
case R_AARCH64_TLS_TPREL64:
^~~~~~~~~~~~~~~~~~~~~
linker.cpp:3160:12: error: 'R_AARCH64_TLS_DTPREL32' was not declared in
this scope
case R_AARCH64_TLS_DTPREL32:
Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
> linker.cpp: Fix issue with newer glibc

- hybris/common/hooks.c
In case getaddrinfo fails we may not process the res parameter.
> hybris: fix getaddrinfo error case

- hybris/tests/test_hwcomposer.cpp
It's done the same way in https://github.com/mer-hybris/qt5-qpa-hwcomposer-plugin/blob/master/hwcomposer/hwcomposer_backend_v11.cpp#L229
This fixes test_hwcomposer on MediaTek Helio X10 device (Xiaomi Redmi Note 2), as otherwise HWC will freeze if there are no other displays connected.
> Assign the layer list only to the first display

- hybris/egl/platforms/common/eglplatformcommon.cpp
For me, the change in L119 fixes Plasma display in KWin.
L77 was changed to align, as we probably want to treat RGBA and BGRA equally here.
Fixes some problems related to #382.
> Fix BGRA format conditions in eglplatformcommon

- hybris/common/hooks.c
If sdk_version is higher than the highest version we have implemented
or support in this build, then prefer the highest available linker.
> hybris: prefer the highest available linker, if it makes sense.

- hybris/glesv1/glesv1_cm.c
- hybris/glesv2/glesv2.c
> hybris: Use correct struct in glEGLImageTargetTexture2DOES of glesv2

- hybris/common/n/linker_gdb_support.cpp
With default bionic's implementation, the list of loaded libraries
for GDB is reset when the first Android lib is loaded.
With libhybris, we want to get both Android and Glibc loaded libraries.
However, we shouldn't simply link our "link_map" pointers in the
current list, because glibc's "link_map" object shouldn't point to
our incompatible "link_map" objects. To avoid that:
1. make a copy of the initial list, to avoid modifying glibc's objects
2. prepend our objects to the list, instead of appending it
That way glibc's objects are never modified, and glibc's linker won't
try to manipulate objects that haven't been initialized by him.
> linker N: Improve gdb support

- hybris/egl/platforms/wayland/eglplatform_wayland.cpp
When an EGL app wants to retrieve the default EGL display, it calls eglGetDisplay(0).
However this results in a crash in wayland, when the platform is "wayland".
To solve this, handle the case when the app simply wants to connect to the default display by connecting to the current wayland display.
> waylandws_GetDisplay: handle default display

- hybris/common/hooks.c
This is needed for Android 5.1, to avoid having syscalls
changing errno in bionic's TLS array.
This change is related to https://github.com/ubports/android_bionic/pull/1
> hooks: add hook for __set_errno_internal

- hybris/libnfc_ndef_nxp/libnfc_ndef_nxp.c
- hybris/libnfc_nxp/libnfc_nxp.c
- utils/generate_nfc/README
- utils/generate_nfc/README.android-src
- utils/generate_nfc/generate.sh
- utils/generate_nfc/generate_wrappers.py
- utils/generate_nfc/linux/README
- utils/generate_nfc/linux/pn544.h
- utils/generate_nfc/symbols/README
- utils/generate_nfc/symbols/libnfc.so.txt
- utils/generate_nfc/symbols/libnfc_ndef.so.txt
Since the external `libhybris-nfc-wrapper-generator` repository does not exist anymore, I've dug out the old code and created a PR so that the wrapper scripts live in the same repos as libhybris proper.
The original history of the other repo is included, I decided to remove the submodule references for the Android source code to not unnecessarily bloat checkouts, checkout commit 36f0399 for the vanilla state of `libhybris-nfc-wrapper-generator`.
> Add NFC wrapper generator scripts

- hybris/egl/platforms/wayland/Makefile.am
The file wayland-android-client-protocol.h is generated and thus present
in the build directory. When compiling out of source tree, a build dir
include path is thus missing.
> hybris: add missing top_builddir include in egl/platforms/wayland

- hybris/egl/platforms/wayland/wayland_window.cpp
Destroying an EGLSurface object in the main thread while a rendering thread is calling eglSwapBuffers() results in various crash / hanging scenarios:
* a segfault in dequeueBuffer() while calling m_window->width();
* a hang in finishSwap() because readQueue() is called blocking on the frame_callback, while this ressource have been killed already and there will be no event in the queue;
* a segfault in finishSwap() while creating the frame_callback with m_window->surface.
This PR is adding more protection against illegal use of m_window, even if the case described above is an illegal case (calling destroying a window while the rendering thread is swapping it). It should solve #402.
What do you think?
> Fix crashes in threaded EGL wayland rendering

- hybris/common/mm/dlfcn.cpp
- hybris/common/n/dlfcn.cpp
Some android 8 adaptations need these hooks. To make sure the hooks are also active in older adaptations add "extern "C"" to the definitions. Otherwise those would be stubs which might cause issues.
> hybris: make sure all linker functions that we need in hooks.c are unmangled.

- hybris/common/hooks.c
- hybris/common/jb/linker.c
- hybris/common/mm/linker.cpp
- hybris/common/n/linker.cpp
- hybris/common/n/linker_gdb_support.cpp
- hybris/common/n/linker_gdb_support.h
- hybris/common/o/linker_gdb_support.cpp
- hybris/common/o/linker_gdb_support.h
- hybris/common/o/linker_main.cpp
There are still some conflicts between android libs and glibc libs in the
gdb lib map.
Very likely, in most cases, the developer only wants to debug the glibc
related code, and is not interested in seeing the Android stack.
Therefore, introduce an env. variable and disable linking of android
libs by default.
> jb/mm/n: HYBRIS_ENABLE_LINKER_DEBUG_MAP enables Android libs in gdb

- hybris/common/n/linker_gdb_support.cpp
- hybris/common/o/linker_gdb_support.cpp
In previous commit some variables were incorrectly named.
> hybris: n/o: Fix variable naming mismatch. Cleanup whitespaces.

- hybris/egl/platforms/wayland/eglplatform_wayland.cpp
`hybris_egl_display_get_mapping()`  function is implemented
in libhybris's libEGL.so. However, eglplatform_wayland.so
is not linked to libEGL directly, causing undefined symbol
errors during loading, if libEGL was not already loaded by
some other dependencies. Therefore, we should try
to load libEGL at runtime here and resolve this function
dynamically.
Error is seen at startup of Plasma Mobile in postmarketOS, for example:
```
klte:~$ cat /tmp/plasmashell_logs 
Error: could not determine $DISPLAY.
org.kde.kwindowsystem: Loaded plugin "/usr/lib/qt5/plugins/kf5/org.kde.kwindowsystem.platforms/KF5WindowSystemKWaylandPlugin.so" for platform "wayland"
Using Wayland-EGL
ERROR: /usr/lib/libhybris/eglplatform_wayland.so
Error relocating /usr/lib/libhybris/eglplatform_wayland.so: …
```
> eglplatform_wayland: load libEGL at runtime

- hybris/include/hybris/properties/properties.h
This removes a unnecessary header that got included in properties.h, as
hybris_properties.c does not include this file there is no reason
libraries that link to it should.
Also libandroid-properties.pc does not require this, so builds depending
on properties will fail to build.
> Remove unnecessary header

- hybris/egl/platforms/common/eglplatformcommon.cpp
- hybris/egl/platforms/wayland/eglplatform_wayland.cpp
Increased to fit the extensions on Sony Tama/Akari.
On that device, I had maximal length of strings equal to
```
eglplatformcommon_eglQueryString max string length: 1060
waylandws_eglQueryString max string length: 1133
```
> eglplatform: increase eglextensionsbuf

- hybris/common/mm/linker.cpp
- hybris/common/n/linker.cpp
- hybris/common/o/linker_main.cpp
When HYBRIS_LD_LIBRARY_PATH is set and security conditions are met, prefer the library path set by that variable. Otherwise, use the path from DEFAULT_HYBRIS_LD_LIBRARY_PATH.
It seems to me that this was original intention in the provided linkers and is as it is done in `hybris/common/jb/linker.c`. 
This PR allows to set the environment as in Flatpak sandbox and use it for accessing GL and other drivers.
> Prioritize library path set by HYBRIS_LD_LIBRARY_PATH environment variable

- compat/hwc2/hwc2_compatibility_layer.cpp
Check if presentFence is a valid pointer before calling dup(), which can happen if HWC2::Display::present() fails for some reason.
Tested to fix random lipstick crashes on Redmi Note 7 (lavender).
> hybris: hwc2: avoid crash in hwc2_compat_display_present

- hybris/egl/platforms/common/eglplatformcommon.cpp
The string returned by eglplatformcommon_eglQueryString already ends with a space,
adding an additional one causes crashes (tested on a PowerVR device).
Before:
An additional space was visible before EGL_EXT_swap_buffers_with_damage.
After:
This probably needs verification on other devices
> egl: wayland: Remove additional space before EGL_EXT

- hybris/gralloc/gralloc.c
If HAS_GRALLOC1_HEADER is defined but the device doesn't actually
support gralloc1 then `gralloc1_open` may succeed but the callbacks in
the structure are all NULL. Check the `module_api_version` field before
calling `gralloc1_open` following `Loader::Loader()` in
frameworks/native/libs/ui/Gralloc1.cpp. This fixes a segfault with the
binary libs for Samsung herolte.
> hybris: fix crash when gralloc1 not supported on the device

- hybris/configure.ac
- hybris/properties/Makefile.am
The `.la` path should be relative to the build directory not source.
Also fix invalid shell variable name `ubuntu-camera-headers`.
> hybris: fix out of tree builds

- hybris/egl/ws.c
These commits solve two issues:
1. Solves #443 where a multi threaded call to `_init_ws` (while another thread has not yet completed `_init_ws`) leads to a second call of `hybris_gralloc_initialize` which then fails because it has already completed the initialization of the gralloc module.
2. Solves subsequent crashes of `kdeinit` because `HYBRIS_EGLPLATFORM` is reset to "" but it is not unset (it's still defined). This leads to `_init_ws` trying to load the file `eglplatform_.so` which obviously does not exist.
Therefore, fallback to the default EGL platform in case the environment variable is defined but empty.
> Prevent race condition on multi thread init of ws. Solves #443

- compat/camera/camera_compatibility_layer.cpp
- compat/media/media_recorder.cpp
postRecordingFrameHandleTimestamp has been ifdef'ed in camera_control.h
but not in camera_compatibility_layer.cpp, which cause "no member
function declared" compile error on Android 5. Add the matching ifdef to
fix it.
Namespace android::hardware doesn't exist on Android 5 or lower. Ifdef
the namespace alias to fix compilation.
Change-Id: I903b66116d35cb9851d88f0723a434bce8f84b04
> compat: fix compilation on Android 5 or lower

- hybris/common/hooks.c
Bionic does not have this attribute for struct __sFILE definition. Fixes struct size mismatch on aarch64 (used to be 144 vs 152 on Android), which resulted in crash of code using stdout/stderr symbols like fprintf(stderr, ...) found in MTK audio HAL.
Thanks to @krnlyng for noticing this.
> hooks: remove __attribute__((packed)) from struct bionic_file

- hybris/egl/platforms/common/nativewindowbase.cpp
Fix handling requests for NATIVE_WINDOW_MAX_BUFFER_COUNT
in functions _query() and _native_query_operation()
what is required in Android 8 and newer.
> Fix handling max buffer count. JB#51520

- hybris/common/Makefile.am
- hybris/common/dso_handle_counters.cpp
- hybris/common/dso_handle_counters.h
- hybris/common/hooks.c
This function is used by the compiler to destruct `thread_local`
variables at thread's exit. Virtually no one uses it, but I planed to
use to solve libmedia_compat_layer's problem when using remote codec.
This implementation wraps dtor so that we can do reference counting.
This prevents memory leak when a library is dlclose'd, at the expense
of more memory usage and more code to execute.
For an implementation that doesn't wrap dtor, see #456.
> hybris: hook __cxa_thread_atexit (wrap dtor)

- hybris/egl/platforms/wayland/wayland_window.cpp
Some EGL implementations rightfully doesn't ask the default width
and height of the NativeWindow until transform hint changes, so
SET_BUFFERS_DIMENSIONS is never called. This results in the EGL
surface not being resized when wl_egl_window_resize() is called on
the window.
With this commit WaylandNativeWindow::resize() will set both default
and current dimensions and each buffer will be reallocated as soon as
it is dequeued.
> [egl] Set buffer dimensions on window resize. JB#52698

- hybris/common/Makefile.am
- hybris/common/jb/dlfcn.c
- hybris/common/jb/linker.c
- hybris/common/wrapper_code.h
- hybris/common/wrapper_code_generic_arm.c
- hybris/common/wrappers.c
- hybris/egl/platforms/wayland/wayland_window.cpp
- hybris/gralloc/gralloc.c
- hybris/include/hybris/gralloc/gralloc.h
While adding the gralloc1 support we broke devices which use QCOM_BSP.
This fixes it and adds tracing support to the jb linker.
> Fix for devices which use qcom bsp and jb linker tracing.

- hybris/tests/Makefile.am
If Wayland is not selected/available during the build, the compilation of `test_camera` fails because it relies on Wayland being available.
> Exclude test_camera if Wayland is not available

- hybris/tests/test_common.cpp
Needed for ANDROID_VERSION_MAJOR/ANDROID_VERSION_MINOR defines. Fixes layer->planeAlpha not getting set.
> hybris: tests: fix missing android-config.h include in test_common

- utils/load_sym_files.py
Unlike using subprocess.Popen() directly, subprocess.check_output() will
throw if running the command fails. This helps catching when objdump is
not installed, as otherwise the script will silently use the wrong
output, causing confusion. subprocess.check_output() is available in
Python 2.7 and 3.1+.
While we're at it, stop using shell and pass arguments directly.
> load_sym_files: switch to subprocess.check_output()

- hybris/egl/egl.c
In case Android environment is not available but libhybris's EGL is
loaded via libglvnd, it should gracefully fail instead of segfault. This
time, don't crash when libhybris is unable to find eglGetProcAddress;
just return NULL instead. libglvnd will understand.
> egl: don't crash if eglGetProcAddress is not available

- hybris/tests/Makefile.am
The Vulkan test will fail to compile when the relevant headers do not exist.
> hybris: tests: Don't build vulkan test when headers aren't available.

- hybris/egl/egl.c
Since https://github.com/libhybris/libhybris/commit/a1bf776f4c06caba8078c7335deb766b3a77fdf1 the eglGetPlatformDisplay() function has been implemented. This function is part of EGL 1.5.
Some platforms rely on the existence of this function to detect if EGL 1.5 is supported [^1].
However, libhybris does not implement all EGL 1.5 functions, this provides the implementation for the eglCreatePlatformWindowSurface() function to fix a compilation issue with Qt [^2].
It's worth noting that the eglCreatePlatformWindowSurface() function and the eglCreateWindowSurface() function are not identical.
Similar to https://github.com/libhybris/libhybris/commit/362efd97cd5b18f580c402d3fc14555f1ef6e31e we might need to implement additional type conversions at a later stage.
[^1]: …
> hybris: egl: Provide eglCreatePlatformWindowSurface.

- hybris/common/q/hybris_compat.h
- hybris/common/q/linker.cpp
glibc-2.36 introduces its own support for relative relocations, and does so using different constants, breaking the q linker.
Rename the Android-specific constants to DT_ANDROID_, and define (and check) the new ones if needed. Since api level 30, bionic switched to those as well [0].
[0] https://github.com/aosp-mirror/platform_bionic/commit/6663f5525dafc31de1891d7e0fa6da88c4c7dc4b
> hybris: q: rename RELR sections defines to DT_ANDROID_RELR

- hybris/include/EGL/eglplatform.h
When using Qt, the USE_X11 define can be present even when no X11 headers are there. This leads to build issues when trying to include X11/Xlib.h.
As before commit d31230d854c7041a48be64047b939b09dd23f580 , take into account MESA_EGL_NO_X11_HEADERS to exclude X11.
> eglplatform.h: take MESA_EGL_NO_X11_HEADERS into account

- .gitignore
- hybris/common/hooks.c
- hybris/configure.ac
- hybris/egl/egl.c
- hybris/egl/eglhybris.h
- hybris/egl/platforms/common/eglnativewindowbase.h
- hybris/hwc2/hwc2.c
- hybris/include/hybris/gralloc/gralloc.h
- hybris/libsync/sync.c
- hybris/platforms/common/nativewindowbase.cpp
- hybris/platforms/common/nativewindowbase.h
- hybris/platforms/common/platformcommon.h
- hybris/platforms/common/server_wlegl.cpp
- hybris/platforms/common/server_wlegl.h
- hybris/platforms/common/server_wlegl_buffer.h
- hybris/platforms/common/server_wlegl_handle.h
- hybris/platforms/common/windowbuffer.h
- hybris/ui/ui.c
Add missing hook for pthread_setschedprio. Make sure android-config.h is always included before any Android headers. Update .gitignore file to match current builds.
> Add support for Android 12 and 13

- hybris/common/q/Makefile.am
- hybris/common/q/bionic/libc/bionic/bionic_call_ifunc_resolver.cpp
- hybris/common/q/bionic/libc/include/sys/ifunc.h
- hybris/common/q/bionic/libc/private/bionic_call_ifunc_resolver.h
- hybris/common/q/linker.cpp
From https://android.googlesource.com/platform/bionic/+/e949195. Needed for Android 12 binaries as tested on a MediaTek device.
> hybris: q: backport ifunc resolvers calling convention from R linker

- hybris/gralloc/gralloc.c
Some devices have dummy gralloc.default.so module which gets loaded so trying to use libui first makes graphics work in such cases. Using gralloc is still the fallback if libui is not present.
> hybris: gralloc: Use libui's GraphicBufferAllocator/GraphicBufferMapper by default

- hybris/common/mm/linker.cpp
- hybris/common/n/linker.cpp
- hybris/common/o/linker_soinfo.cpp
- hybris/common/q/linker_soinfo.cpp
Since fc7bfd1b, the soinfo structure fields are uninitialised. But this is creating an issue in linker_main.cpp#823, where a temporary soinfo object is created, but its `handle_` member is not set. Then, on exit of the function, the temporary object is destroied and it mentions in Valgrind a use of an uninitialised value with the following backtrace:
```
==22274== Use of uninitialised value of size 8
==22274==    at 0x9685BB8: soinfo::~soinfo() (in /usr/lib64/libhybris/linker/q.so)
==22274==    by 0x9682B3F: android_linker_init (in /usr/lib64/libhybris/linker/q.so)
==22274==    by 0x6C363DF: ??? (in /usr/lib64/libhybris-common.so.1.0.0)
==22274==    by 0x6C36E2B: android_dlopen (in /usr/lib64/libhybris-common.so.1.0.0)
==22274==    by 0x10B0EB: __load_library (in …
```
> Avoid uninitialised handle_ in soinfo.

- hybris/common/hooks.c
Needed on SM8475 with API 31 vendor, found on Xiaomi 12 Pro
> hybris: Hook pthread_mutexattr_(get/set)protocol

- hybris/egl/platforms/hwcomposer/eglplatform_hwcomposer.cpp
This pull request removes the arbitrary limit of one native window inside the hwcomposer platform.
> hybris: eglplatform_hwcomposer: allow creating multiple native windows

- hybris/common/hooks.c
Needed by audio HAL on QCM6490 with API 30 vendor (found on FP5):
```
calling unhooked method: _ZN14PerfThreadPoolC2Ev@0x7fe8b2c8cc
calling hooked method: getpid@0x7ff7af5d30
calling hooked method: pthread_self@0x7ff7ac5ab8
calling hooked method: pthread_getname_np@0xfffffffffffffffe
Thread 1 "pulseaudio" received signal SIGBUS, Bus error.
0xfffffffffffffffe in ?? ()
```
> hybris: Hook pthread_getname_np

- hybris/common/q/linker.cpp
without this patch android prebuilt objects will throw a bunch of linker warnings like so:
```
WARNING: linker Warning: "/android/vendor/lib64/android.hardware.media.c2@1.0.so" unused DT entry: unknown processor-specific (type 0x70000001 arg (nil)) (ignoring)
WARNING: linker Warning: "/android/vendor/lib64/android.hardware.media.c2@1.1.so" unused DT entry: unknown processor-specific (type 0x70000001 arg (nil)) (ignoring)
WARNING: linker Warning: "/android/vendor/lib64/android.hardware.media.c2@1.0.so" unused DT entry: unknown processor-specific (type 0x70000001 arg (nil)) (ignoring)
WARNING: linker Warning: "/android/vendor/lib64/libcodec2_vndk.so" unused DT entry: unknown processor-specific (type 0x70000001 arg (nil)) (ignoring)
WARNING: linker Warning: …
```
> hybris: q: ignore DT_AARCH64_* processor specific DT

- hybris/egl/ws.c
Make libhybris respect exactly one EGL WS at a time (though also seems to be limit as to how many different EGL Displays can be given, so that support seems out of scope for this one).
This resolves an issue where eglinfo would attempt libEGL probing for various EGL platform types, allowing both the Android and Wayland WS to be used in sequence (not in parallel).
> hybris/egl/ws: Allow hot-reloading by unloading previous WS

- hybris/common/q/hybris_compat.h
Defined were missing from https://github.com/libhybris/libhybris/pull/550
> q: Add missing dynamic array tag defines

- hybris/platforms/common/nativewindowbase.cpp
- hybris/platforms/common/server_wlegl.cpp
Needed for vulkan support in Android 14 base. Improve debugging of operations and fix a crash if gralloc fails.
> hybris: platforms: common: Add support for NATIVE_WINDOW_GET_CONSUMER_USAGE64

- hybris/common/hooks.c
no behavior changes, just build fixes for latest gcc
> hooks: fix incompatible pointer type error in latest toolchain

- hybris/common/hooks.c
Changed to int.
~Adding the enum as char as the values are small enough and it should work for little-endian.~ 
The actual [enum](https://github.com/libhybris/libhybris/blob/master/hybris/common/q/bionic/libc/include/android/fdsan.h#L166) I didn't try to import from android "Q" headers.
> hook android_fdsan_set_error_level

- hybris/common/q/bionic/libc/bionic/bionic_allocator.cpp
- hybris/common/q/linker_memory.cpp
When using the TLS relocation patches on Android 14 with Ubuntu Touch, we ran into a peculiar issue where the global malloc/calloc/free symbols in libhybris were overwriting the glibc symbols, which caused these symbols to start freeing memory allocated by glibc. Moreover, due to the global symbols being replaced, the commented-out lines didn't work, which they now perfectly do.
Tested on Pixel 7 Pro with Halium 14
> common/q: drop linker_memory and fix allocator free()

- hybris/configure.ac
Since Android 7 system path has had the highest priority in library paths (bionic commit 88f5111123d9900fc4da05435aa8416a6f9f9bcd). In latest Android 14 revision the older order causes symbols loading issues because VNDK is disabled by default which causes some libraries system and vendor to have different set of symbols.
> hybris: Correct default linker path order for Android >= 7

- hybris/egl/glvnd/generate/eglFunctionList.py
- hybris/egl/glvnd/generate/egl_hybris.xml
- hybris/egl/platforms/wayland/eglplatform_wayland.cpp
- hybris/egl/platforms/wayland/wayland_window.cpp
- hybris/egl/platforms/wayland/wayland_window.h
- hybris/platforms/wayland/wayland_window_common.cpp
- hybris/vulkan/platforms/wayland/wayland_window.cpp
- hybris/vulkan/platforms/wayland/wayland_window.h
There is literally no any single user of this undocumented/private API.
The only one user Internet knows about is https://github.com/krnlyng/sfdroid_renderer/commit/17e31ec769214dd41b5e780f902ee94e32940197 ;)
Since then, sfdroid_renderer was replacing it with a more straightforward solution.
> egl: RIP eglHybrisWaylandPostBuffer(EGLNativeWindowType, ANativeWindowBuffer *)

- hybris/platforms/wayland/wayland_window_common.cpp
> wayland: Fix UB in destroyBuffers()
